"""empty message

Revision ID: 0232805dcc6c
Revises: 1cfc15b932a6
Create Date: 2022-02-14 10:11:43.622824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0232805dcc6c'
down_revision = '1cfc15b932a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_tag_key', 'users', type_='unique')
    op.drop_column('users', 'tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_tag_key', 'users', ['tag'])
    # ### end Alembic commands ###
