"""empty message

Revision ID: 10162b8a4036
Revises: 42ca63a8c2d6
Create Date: 2021-12-12 17:50:24.006900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10162b8a4036'
down_revision = '42ca63a8c2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('user_permissions_permission_id_fkey', 'user_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'user_permissions', 'permissions', ['permission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_permissions', type_='foreignkey')
    op.create_foreign_key('user_permissions_permission_id_fkey', 'user_permissions', 'users', ['permission_id'], ['id'])
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
