"""empty message

Revision ID: 1cfc15b932a6
Revises: 83202c481799
Create Date: 2022-02-14 10:10:19.248069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cfc15b932a6'
down_revision = '83202c481799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tag', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['tag'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'tag')
    # ### end Alembic commands ###
