"""empty message

Revision ID: 42ca63a8c2d6
Revises: f6590681d8f8
Create Date: 2021-12-12 01:52:55.468778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ca63a8c2d6'
down_revision = 'f6590681d8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sell_price', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('buy_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'buy_price')
    op.drop_column('products', 'sell_price')
    # ### end Alembic commands ###
