"""empty message

Revision ID: 9ca2741d7748
Revises: 7a9ce6148ff7
Create Date: 2022-01-12 11:23:57.197613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca2741d7748'
down_revision = '7a9ce6148ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.execute("UPDATE users SET username = 'admin' WHERE username IS NULL;")
    op.alter_column('users', 'username', nullable=False)
    op.drop_constraint('users_user_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'user_name')
    op.alter_column('users', 'username', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_user_name_key', 'users', ['user_name'])
    op.drop_column('users', 'username')
    op.alter_column('products', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
