"""empty message

Revision ID: af6ad429c7bd
Revises: 10162b8a4036
Create Date: 2021-12-18 02:54:07.271006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6ad429c7bd'
down_revision = '10162b8a4036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(), nullable=False))
    op.alter_column('products', 'image',
                existing_type=sa.VARCHAR(),
                type_=sa.LargeBinary(),
                existing_nullable=True,
                postgresql_using='image::bytea'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
