"""empty message

Revision ID: b46c6182c5b4
Revises: af6ad429c7bd
Create Date: 2022-01-04 09:35:22.529189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b46c6182c5b4'
down_revision = 'af6ad429c7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.execute('UPDATE products SET created_on = CURRENT_TIMESTAMP WHERE created_on IS NULL;')
    op.alter_column('products', 'created_on', nullable=False)
    op.drop_constraint('products_code_key', 'products', type_='unique')
    op.drop_column('products', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('products_code_key', 'products', ['code'])
    op.drop_column('products', 'created_on')
    # ### end Alembic commands ###
